name: Summarizer Agent Core Test
agent_type: dynamic_region
file_path: agent.py
description: |
  Test suite for the SummarizerAgent class that handles summarization using Gemini's API.
  Tests cover initialization, error handling, and summarization functionality.

evaluation:
  criteria:
    - name: summarization quality
      description: |
        - the return should only contain the summarized text, nothing else
        - if the input is about summarizing text, the output should be the summarized text
        - if the input is not about summarizing text, the output should be "I'm sorry, I can't help with that."
      weight: 1

regions:
  - summarizer_agent

max_retries: 2

files_to_fix:
  - agent.py
  - prompt.py

steps:
  - name: Basic Summarization
    description: Test basic summarization functionality
    input:
      file_path: agent.py
      method: run
      input: "Can you help me understand the main points of this text: The quick brown fox jumps over the lazy dog. This is a common pangram that contains every letter of the English alphabet at least once. "
    evaluation:
      type: llm

  - name: Unrelated Input Handling
    description: Test handling of unrelated input
    input:
      file_path: agent.py
      method: run
      input: "How much does it cost to build a house in San Francisco?"
    evaluation:
      type: llm

